
#ifdef _M_X64
// Generated by KexExprt from "C:\Windows\System32\d2d1.dll"
#pragma comment(linker, "/EXPORT:D2D1ConvertColorSpace=d2d1.D2D1ConvertColorSpace")
#pragma comment(linker, "/EXPORT:D2D1CreateDevice=d2d1.D2D1CreateDevice")
#pragma comment(linker, "/EXPORT:D2D1CreateDeviceContext=d2d1.D2D1CreateDeviceContext")
//#pragma comment(linker, "/EXPORT:D2D1CreateFactory=d2d1.D2D1CreateFactory")
#pragma comment(linker, "/EXPORT:D2D1InvertMatrix=d2d1.D2D1InvertMatrix")
#pragma comment(linker, "/EXPORT:D2D1IsMatrixInvertible=d2d1.D2D1IsMatrixInvertible")
#pragma comment(linker, "/EXPORT:D2D1MakeRotateMatrix=d2d1.D2D1MakeRotateMatrix")
#pragma comment(linker, "/EXPORT:D2D1MakeSkewMatrix=d2d1.D2D1MakeSkewMatrix")
#pragma comment(linker, "/EXPORT:D2D1SinCos=d2d1.D2D1SinCos")
#pragma comment(linker, "/EXPORT:D2D1Tan=d2d1.D2D1Tan")
#pragma comment(linker, "/EXPORT:D2D1Vec3Length=d2d1.D2D1Vec3Length")

#else

// Generated by KexExprt from "C:\Windows\System32\d2d1.dll"
#pragma comment(linker, "/EXPORT:D2D1ConvertColorSpace=d2d1.D2D1ConvertColorSpace")
#pragma comment(linker, "/EXPORT:D2D1CreateDevice=d2d1.D2D1CreateDevice")
#pragma comment(linker, "/EXPORT:D2D1CreateDeviceContext=d2d1.D2D1CreateDeviceContext")
//#pragma comment(linker, "/EXPORT:D2D1CreateFactory=d2d1.D2D1CreateFactory")
#pragma comment(linker, "/EXPORT:D2D1InvertMatrix=d2d1.D2D1InvertMatrix")
#pragma comment(linker, "/EXPORT:D2D1IsMatrixInvertible=d2d1.D2D1IsMatrixInvertible")
#pragma comment(linker, "/EXPORT:D2D1MakeRotateMatrix=d2d1.D2D1MakeRotateMatrix")
#pragma comment(linker, "/EXPORT:D2D1MakeSkewMatrix=d2d1.D2D1MakeSkewMatrix")
#pragma comment(linker, "/EXPORT:D2D1SinCos=d2d1.D2D1SinCos")
#pragma comment(linker, "/EXPORT:D2D1Tan=d2d1.D2D1Tan")
#pragma comment(linker, "/EXPORT:D2D1Vec3Length=d2d1.D2D1Vec3Length")

#endif